use std::collections::HashSet;
use std::path::PathBuf;

use crate::infra::git::{GitOperations, GitWorkspaceInfo};
use crate::infra::git_error::GitError;
use crate::services::agent_workspace::{
    CleanupError, CleanupResult, GitStatus, StatusError, WorkspaceManager,
};
use crate::services::git_checkout_workspace::GitCheckoutWorkspace;
use crate::services::git_worktree_workspace::GitWorktreeWorkspace;

pub struct GlobalWorkspaceManager<G: GitOperations> {
    worktree_workspaces: GitWorktreeWorkspace<G>,
    checkout_workspaces: GitCheckoutWorkspace<G>,
}

impl<G: GitOperations> GlobalWorkspaceManager<G> {
    pub fn new(worktree: GitWorktreeWorkspace<G>, checkout: GitCheckoutWorkspace<G>) -> Self {
        Self {
            worktree_workspaces: worktree,
            checkout_workspaces: checkout,
        }
    }
}

impl<G: GitOperations + Clone> GlobalWorkspaceManager<G> {
    pub fn with_git(git: G) -> Self {
        let worktree = GitWorktreeWorkspace::new(git.clone());
        let checkout = GitCheckoutWorkspace::new(git);
        Self::new(worktree, checkout)
    }
}

impl<G: GitOperations> WorkspaceManager for GlobalWorkspaceManager<G> {
    fn get_statuses(&self, show_all: bool) -> Result<Vec<GitStatus>, StatusError> {
        Ok([
            self.worktree_workspaces.get_statuses(show_all)?,
            self.checkout_workspaces.get_statuses(show_all)?,
        ]
        .concat())
    }

    fn cleanup(
        &self,
        excluded_paths: &HashSet<PathBuf>,
        all: bool,
        force: bool,
    ) -> Result<CleanupResult, CleanupError> {
        Ok([
            self.worktree_workspaces
                .cleanup(excluded_paths, all, force)?,
            self.checkout_workspaces
                .cleanup(excluded_paths, all, force)?,
        ]
        .into_iter()
        .reduce(|mut acc, item| {
            acc.extend(item);
            acc
        })
        .unwrap_or_default())
    }

    fn get_all(&self) -> Result<Vec<GitWorkspaceInfo>, GitError> {
        Ok([
            self.worktree_workspaces.get_all()?,
            self.checkout_workspaces.get_all()?,
        ]
        .concat())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::infra::git::{GitWorkspaceInfo, MockGitOperations};
    use std::collections::HashSet;
    use std::path::PathBuf;

    // MockGit is deprecated in favour of MockGitOperations generated by mockall automock.
    #[deprecated(note = "Use MockGitOperations from mockall automock instead")]
    #[allow(dead_code)]
    #[derive(Clone)]
    struct MockGit {
        repo_root: PathBuf,
        project_name: String,
        worktrees: Vec<GitWorkspaceInfo>,
        base_branch: String,
        uncommitted_changes: Vec<(PathBuf, bool, usize)>,
        divergence: Vec<(PathBuf, usize, usize)>,
    }

    #[allow(deprecated)]
    impl GitOperations for MockGit {
        fn get_repo_root(&self) -> Result<PathBuf, crate::infra::git_error::GitError> {
            Ok(self.repo_root.clone())
        }

        fn get_project_name(&self) -> Result<String, crate::infra::git_error::GitError> {
            Ok(self.project_name.clone())
        }

        fn create_worktree(
            &self,
            _path: &std::path::Path,
            _branch: &str,
        ) -> Result<(), crate::infra::git_error::GitError> {
            Ok(())
        }

        fn list_worktrees(
            &self,
        ) -> Result<Vec<GitWorkspaceInfo>, crate::infra::git_error::GitError> {
            Ok(self.worktrees.clone())
        }

        fn remove_worktree(
            &self,
            _path: &std::path::Path,
        ) -> Result<(), crate::infra::git_error::GitError> {
            Ok(())
        }

        fn get_default_remote_branch(
            &self,
        ) -> Result<String, crate::infra::git_error::GitError> {
            Ok(self.base_branch.clone())
        }

        fn get_status_porcelain(
            &self,
            worktree_path: &std::path::Path,
        ) -> Result<String, crate::infra::git_error::GitError> {
            for (path, has_changes, count) in &self.uncommitted_changes {
                if path == worktree_path {
                    if *has_changes {
                        let lines: Vec<String> =
                            (0..*count).map(|i| format!(" M file{}.txt", i)).collect();
                        return Ok(lines.join("\n"));
                    } else {
                        return Ok(String::new());
                    }
                }
            }
            Ok(String::new())
        }

        fn count_commits_ahead(
            &self,
            worktree_path: &std::path::Path,
            _base_branch: &str,
        ) -> Result<usize, crate::infra::git_error::GitError> {
            for (path, ahead, _) in &self.divergence {
                if path == worktree_path {
                    return Ok(*ahead);
                }
            }
            Ok(0)
        }

        fn count_commits_behind(
            &self,
            worktree_path: &std::path::Path,
            _base_branch: &str,
        ) -> Result<usize, crate::infra::git_error::GitError> {
            for (path, _, behind) in &self.divergence {
                if path == worktree_path {
                    return Ok(*behind);
                }
            }
            Ok(0)
        }

        fn clone_local(
            &self,
            _source: &std::path::Path,
            _dest: &std::path::Path,
        ) -> Result<(), crate::infra::git_error::GitError> {
            Ok(())
        }

        fn checkout_new_branch(
            &self,
            _path: &std::path::Path,
            _branch: &str,
        ) -> Result<(), crate::infra::git_error::GitError> {
            Ok(())
        }

        fn get_current_branch(
            &self,
            _path: &std::path::Path,
        ) -> Result<Option<String>, crate::infra::git_error::GitError> {
            Ok(None)
        }
    }

    #[test]
    fn test_get_statuses_combines() {
        let repo_root = PathBuf::from("/repo");
        let wt1_path = PathBuf::from("/wt1");

        let worktrees = vec![
            GitWorkspaceInfo {
                path: repo_root.clone(),
                branch: Some("main".to_string()),
            },
            GitWorkspaceInfo {
                path: wt1_path.clone(),
                branch: Some("branch".to_string()),
            },
        ];

        let mut worktree_mock = MockGitOperations::new();
        worktree_mock
            .expect_list_worktrees()
            .return_once(move || Ok(worktrees));
        worktree_mock
            .expect_get_default_remote_branch()
            .returning(|| Ok("origin/main".to_string()));
        worktree_mock
            .expect_get_status_porcelain()
            .returning(|_| Ok(String::new()));
        worktree_mock
            .expect_count_commits_ahead()
            .returning(|_, _| Ok(0));
        worktree_mock
            .expect_count_commits_behind()
            .returning(|_, _| Ok(0));

        let mut checkout_mock = MockGitOperations::new();
        checkout_mock
            .expect_get_project_name()
            .returning(|| Ok("test-project".to_string()));
        checkout_mock
            .expect_get_default_remote_branch()
            .returning(|| Ok("origin/main".to_string()));

        let worktree = GitWorktreeWorkspace::new(worktree_mock);
        let checkout = GitCheckoutWorkspace::new(checkout_mock);
        let service = GlobalWorkspaceManager::new(worktree, checkout);

        let statuses = service.get_statuses(true).unwrap();

        assert_eq!(statuses.len(), 1);
        assert!(statuses.iter().any(|s| s.path == wt1_path));
    }

    #[test]
    fn test_cleanup_combines() {
        let repo_root = PathBuf::from("/repo");

        let mut worktree_mock = MockGitOperations::new();
        worktree_mock
            .expect_list_worktrees()
            .return_once(|| Ok(vec![]));
        worktree_mock
            .expect_get_repo_root()
            .returning(move || Ok(repo_root.clone()));
        worktree_mock
            .expect_get_default_remote_branch()
            .returning(|| Ok("origin/main".to_string()));

        let mut checkout_mock = MockGitOperations::new();
        checkout_mock
            .expect_get_project_name()
            .returning(|| Ok("test-project".to_string()));
        checkout_mock
            .expect_get_default_remote_branch()
            .returning(|| Ok("origin/main".to_string()));

        let worktree = GitWorktreeWorkspace::new(worktree_mock);
        let checkout = GitCheckoutWorkspace::new(checkout_mock);
        let service = GlobalWorkspaceManager::new(worktree, checkout);

        let result = service.cleanup(&HashSet::new(), true, false).unwrap();

        assert_eq!(result.removed.len(), 0);
        assert_eq!(result.skipped.len(), 0);
    }

    #[test]
    fn test_get_all_combines() {
        let wt1_path = PathBuf::from("/wt1");

        let mut worktree_mock = MockGitOperations::new();
        worktree_mock
            .expect_list_worktrees()
            .return_once(move || {
                Ok(vec![GitWorkspaceInfo {
                    path: wt1_path.clone(),
                    branch: Some("branch".to_string()),
                }])
            });

        let mut checkout_mock = MockGitOperations::new();
        checkout_mock
            .expect_get_project_name()
            .returning(|| Ok("test-project".to_string()));

        let worktree = GitWorktreeWorkspace::new(worktree_mock);
        let checkout = GitCheckoutWorkspace::new(checkout_mock);
        let service = GlobalWorkspaceManager::new(worktree, checkout);

        let all = service.get_all().unwrap();

        assert_eq!(all.len(), 1);
        assert!(all.iter().any(|w| w.path == PathBuf::from("/wt1")));
    }
}
